/**
 * Wikilink parser — extracts [[wikilinks]] from Obsidian markdown.
 * Handles aliases [[path|display text]] and heading anchors [[path#section]].
 */
import { logger } from "../utils/logger.js";

export interface ParsedWikilink {
  /** Raw match text (e.g., "[[daily/2026-06-19]]") */
  raw: string;
  /** Target path (e.g., "daily/2026-06-19") */
  targetPath: string;
  /** Display text if aliased (e.g., "display text" from [[path|text]]) */
  displayText: string;
  /** Section anchor if present (e.g., "section" from [[path#section]]) */
  sectionAnchor: string;
  /** Surrounding context in the source document */
  contextSnippet: string;
  /** Whether this link was auto-generated (false for explicit markdown links) */
  isAutoGenerated: boolean;
}

/**
 * Regex for Obsidian wikilinks: [[target]], [[target|alias]], [[target#anchor]], [[target#anchor|alias]]
 */
const WIKILINK_REGEX = /\[\[([^\]|#]+)(?:#([^\]|]+))?(?:\|([^\]]+))?\]\]/g;

/**
 * Parse all wikilinks from markdown content.
 */
export function parseWikilinks(
  content: string,
  isAutoGenerated: boolean = false
): ParsedWikilink[] {
  const links: ParsedWikilink[] = [];
  const matches = content.matchAll(WIKILINK_REGEX);

  for (const match of matches) {
    const raw = match[0];
    const targetPath = (match[1] || "").trim();
    const sectionAnchor = (match[2] || "").trim();
    const displayText = (match[3] || "").trim();

    // Get context snippet (±50 chars around the link)
    const matchIndex = match.index || 0;
    const contextStart = Math.max(0, matchIndex - 50);
    const contextEnd = Math.min(content.length, matchIndex + raw.length + 50);
    const contextSnippet = content.slice(contextStart, contextEnd).replace(/\n/g, " ");

    links.push({
      raw,
      targetPath,
      displayText: displayText || targetPath,
      sectionAnchor,
      contextSnippet,
      isAutoGenerated,
    });
  }

  return links;
}

/**
 * Resolve a wikilink target path to a vault-relative path.
 * Tries common patterns: with/without .md, in subdirectories.
 */
export function resolveWikilinkPath(
  targetPath: string,
  existingPaths: Set<string>
): string | null {
  // Normalize: remove leading/trailing slashes
  let normalized = targetPath.replace(/^\/+|\/+$/g, "");

  // Try exact match first
  const withMd = normalized.endsWith(".md") ? normalized : normalized + ".md";
  if (existingPaths.has(withMd)) return withMd;

  // Try without .md extension
  const withoutMd = normalized.replace(/\.md$/, "");
  if (existingPaths.has(withoutMd + ".md")) return withoutMd + ".md";

  // Try common directory prefixes
  const prefixes = ["daily/", "decisions/", "moc/", "metrics/", "conflicts/", "templates/", "学习计划/"];
  for (const prefix of prefixes) {
    const candidate = prefix + normalized + (normalized.endsWith(".md") ? "" : ".md");
    if (existingPaths.has(candidate)) return candidate;
  }

  // Try as-is in any subdirectory
  for (const path of existingPaths) {
    if (path.endsWith("/" + normalized) || path.endsWith("/" + normalized + ".md")) {
      return path;
    }
  }

  return null;
}

/**
 * Build a set of all known vault paths from memory_nodes.
 */
export function buildPathSet(paths: string[]): Set<string> {
  return new Set(paths.map(p => p.replace(/\\/g, "/")));
}
